name: Workflow Commands

on:
  workflow_dispatch:
  
jobs:
  examples:
    name: Examples
    
    runs-on: ubuntu-latest
    
    env:
      MY_SECRET: "THIS VALUE SHOULD BE HIDDEN FROM THE LOG"

    steps:
      # Works the same as actions/toolkit's core.debug() method
      # - requires the ACTIONS_STEP_DEBUG secret be set to true
      # - only do this if you want to see extended debug information from all steps
      - name: 'Debug messages'
        run: |
          echo "The following debug message should show up in the workflow run Annotation"
          echo "::debug::Debug: Set the Octocat variable"

      # Works the same as actions/toolkit's core.notice() method
      - name: 'Annotation Notice messages'
        run: |
          echo "The following notice messages should show up in the workflow run Annotation"
          echo "::notice file=app.js,line=2,col=10,endCol=20,title=Poorly chosen variable name (notice)::This is not a descriptive name for a variable"
          echo "::notice file=app.js,line=3,endLine=10,title=Duplicate code (notice)::Code is duplicated, consider moving to a method"

      # Works the same as actions/toolkit's core.warning() method
      - name: 'Annotation Warning messages'
        run: |
          echo "The following warning messages should show up in the workflow run Annotation"
          echo "::warning file=app.js,line=4,col=10,endCol=20,title=Poorly chosen variable name (warning)::This is not a descriptive name for a variable"
          echo "::warning file=app.js,line=5,endLine=10,title=Duplicate code (warning)::Code is duplicated, consider moving to a method"

      # Works the same as actions/toolkit's core.error() method
      - name: 'Annotation Error messages'
        run: |
          echo "The following error messages should show up in the workflow run Annotation"
          echo "::error file=app.js,line=7,col=10,endCol=20,title=Poorly chosen variable name (error)::This is not a descriptive name for a variable"
          echo "::error file=app.js,line=8,endLine=10,title=Duplicate code (error)::Code is duplicated, consider moving to a method"

      # Works the same as actions/toolkit's core.startGroup(), core.endGroup method
      - name: Grouping messages
        run: |
          echo "::group::The Seven Dwarfs"
          echo "Bashful"
          echo "Grumpy"
          echo "Dopey"
          echo "Sleepy"
          echo "Doc"
          echo "Sneezy"
          echo "Happy"
          echo "::endgroup::"

      # Works the same as actions/toolkit's core.setSecret() method
      - name: Masking a value in a log
        run: |
          echo "Masking a value"
          echo "::add-mask::$MY_SECRET"
          echo "The following value should be masked: ${{ env.MY_SECRET }}"

      # Stops processing workflow commands
      - name: Stop processing of workflow commands
        run: |
          echo "Disable workflow commands"
          echo "Commands after are disabled"
          stopMarker=$(uuidgen)
          echo "::stop-commands::$stopMarker"
          echo '::warning::This command should be disabled and not displayed'
          echo '::warning::This command should be disabled and not displayed'
          dir
          echo '::warning::This command should be disabled and not displayed'
          echo "::$stopMarker::"
          echo "Commands are enabled again"

      # Works the same as actions/toolkit's core.exportVariable() method
      # Environment variables cannot be accessed in the same step
      - name: Set environment variables
        run: |
          echo "Set environment variables"
          echo "myVariable1=Pink is the color of money" >> $GITHUB_ENV
          echo "myvariable1=Variable names are case-sensitive" >> $GITHUB_ENV

      - name: Read environment variables
        run: |
          echo "Read environment variables"
          echo "myVariable1 - ${{ env.myVariable1 }}"
          echo "myvariable1 - ${{ env.myvariable1 }}"


      # Multiline strings in environment variables
      - name: Multiline strings in environment variables
        run: |
          echo "Multiline strings"
          echo "JSON_RESPONSE<<EOF" >> $GITHUB_ENV
          curl https://microsoft.com >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Read multiline environment variables
        run: |
          echo "Read multiline environment variables"
          echo "JSON_RESPONSE - ${{ env.JSON_RESPONSE }}"

      # Setting step output parameter
      - name: Setting step output parameter
        id: previous-step
        run: |
          echo "Setting step output parameter"
          echo "FavoriteHoliday=April Fools Day" >> $GITHUB_OUTPUT
          
      - name: Read step output parameter
        run: |
          echo "Read step output parameter"
          echo "Output from previous step - ${{ steps.previous-step.outputs.FavoriteHoliday }}"

      # Adding a job summary
      - name: Adding a job summary
        run: |
          echo "Adding a job summary"
          echo "# Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Uses markdown" >> $GITHUB_STEP_SUMMARY
          echo "- :rocket:" >> $GITHUB_STEP_SUMMARY


      # Setting PATH
      - name: Setting PATH
        run: |
          echo "Setting PATH"
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Read PATH
        run: |
          echo "Read PATH"
          echo "$PATH"
